# This workflow keeps our `upstream` branch always in-sync with upstream `main` branch
# Fetches changes every morning, and only applies them if possible Fast-Forward.
on:
  schedule:
    - cron:  '0 8 * * 1-5'
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync upstream branch with upstream/main:latest

    steps:
    - name: Checkout our upstream branch
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        ref: upstream
        fetch-depth: 0

    - name: Pull (Fast-Forward) upstream changes
      run: |
        git remote add upstream https://github.com/strimzi/strimzi-kafka-operator.git
        git fetch upstream main --tags
        git merge --ff-only upstream/main
        git push origin upstream --tags

    - name: Timestamp
      run: date
